# GET https://jsonplaceholder.typicode.com/posts
# GET https://official-joke-api.appspot.com/jokes/random

# HEAD http://api.restful-api.dev/objects
# HEAD https://jsonplaceholder.typicode.com/posts

# POST https://jsonplaceholder.typicode.com/posts
# Authorization: MRT
# Content-Type: application/json
# {
#   "type": "general",
#   "setup": "Hi there",
#   "punchline": "What's up body",
#   "id": 122
# }

OPTIONS https://official-joke-api.appspot.com/jokes/random