# GET https://jsonplaceholder.typicode.com/posts
# HEAD https://official-joke-api.appspot.com/jokes/random

# HEAD http://api.restful-api.dev/objects
# HEAD https://www.lase-peco.com/wp-content/uploads/2026/02/PeCo_Web-Cloud-Entwickler_2026.pdf

